### ISSUE TITLE
`rollup -c` fails to build

### ISSUE THREAD

**Issue by aparkerdavid** [Elderjs/template#35]
From a fresh `degit` and `npm install`:

```
$ npm start

> elderjs-template@1.0.0 start
> npm run build:rollup && npm run dev:server


> elderjs-template@1.0.0 build:rollup
> rollup -c

WARN: Remember to put a valid "origin" in your elder.config.js. This should be a fully qualified domain. This is frequently used plugins and leaving it blank can cause SEO headaches.
Elder.js using rollup in production mode.

./node_modules/intersection-observer/intersection-observer.js → public/static/intersection-observer.js...
created public/static/intersection-observer.js in 428ms

src/components/**/*.svelte → public/svelte...
[!] (plugin svelte) TypeError: Cannot read property 'length' of undefined
src/components/HookDetail.svelte
TypeError: Cannot read property 'length' of undefined
    at sourcemap_add_offset (/Users/parkerrueve/code/elderjs-app/node_modules/svelte/src/compiler/utils/string_with_sourcemap.ts:18:19)
    at get_replacement (/Users/parkerrueve/code/elderjs-app/node_modules/svelte/src/compiler/preprocess/index.ts:112:3)
    at /Users/parkerrueve/code/elderjs-app/node_modules/svelte/src/compiler/preprocess/index.ts:194:12
    at async Promise.all (index 0)
    at replace_async (/Users/parkerrueve/code/elderjs-app/node_modules/svelte/src/compiler/preprocess/index.ts:71:48)
    at preprocess_tag_content (/Users/parkerrueve/code/elderjs-app/node_modules/svelte/src/compiler/preprocess/index.ts:171:15)
    at preprocess (/Users/parkerrueve/code/elderjs-app/node_modules/svelte/src/compiler/preprocess/index.ts:206:3)
    at ModuleLoader.addModuleSource (/Users/parkerrueve/code/elderjs-app/node_modules/rollup/dist/shared/rollup.js:18289:30)
    at ModuleLoader.fetchModule (/Users/parkerrueve/code/elderjs-app/node_modules/rollup/dist/shared/rollup.js:18345:9)
    at async Promise.all (index 2)

npm ERR! code 1
npm ERR! path /Users/parkerrueve/code/elderjs-app
npm ERR! command failed
npm ERR! command sh -c rollup -c

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/parkerrueve/.npm/_logs/2020-11-25T20_46_48_359Z-debug.log
npm ERR! code 1
npm ERR! path /Users/parkerrueve/code/elderjs-app
npm ERR! command failed
npm ERR! command sh -c npm run build:rollup && npm run dev:server

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/parkerrueve/.npm/_logs/2020-11-25T20_46_48_406Z-debug.log
```

**Comment by aparkerdavid** [comment]
Update: build succeeds if the `svelte-preprocess` dependency is pinned at 4.0.9.

**Comment by nickreese** [comment]
@aparkerdavid Wish I would have seen this sooner lol. Just shipped Elder.js v1.2 and had been troubleshooting it myself. It is actually also related to the latest Svelte release from today.

**Comment by aparkerdavid** [comment]
Tried again with the latest version, and sure enough it's working. Thanks!
